# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 FASO DIGITALISATION
# Jaeger with OTLP receiver + Tempo storage backend for latency analysis.
collector:
  otlp:
    enabled: true
    grpc:
      host-port: 4317
    http:
      host-port: 4318

query:
  base-path: /jaeger
  ui:
    config:
      archiveEnabled: true
      dependencies:
        menuEnabled: true
      monitor:
        menuEnabled: true
        # Service Performance Monitoring via spanmetrics
        dotsql: ""
      linkPatterns:
        - type: logs
          key: trace_id
          url: "http://grafana:3000/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22expr%22:%22%7Btrace_id%3D%5C%22#{traceID}%5C%22%7D%22%7D%5D%7D"
          text: "View logs for this trace"

storage:
  type: grpc
  grpc:
    endpoint: faso-tempo:9095
    tls:
      enabled: false
