{{- /* SPDX-License-Identifier: AGPL-3.0-or-later */ -}}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "auth-ms.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-ms.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "auth-ms.fullname" . }}-vault
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: faso/auth-ms/database
        property: url
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: faso/auth-ms/database
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: faso/auth-ms/database
        property: password
    - secretKey: KAYA_PASSWORD
      remoteRef:
        key: faso/auth-ms/kaya
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: faso/auth-ms/jwt
        property: secret
{{- end }}
