{{- /* SPDX-License-Identifier: AGPL-3.0-or-later */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-ms.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-ms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "auth-ms.selectorLabels" . | nindent 4 }}
