# SPDX-License-Identifier: AGPL-3.0-or-later
# SPIRE agent config (K8s PSAT node attestation).
agent {
  data_dir          = "/opt/spire/data/agent"
  log_level         = "INFO"
  log_format        = "JSON"
  server_address    = "spire-server"
  server_port       = "8081"
  socket_path       = "/run/spire/sockets/agent.sock"
  trust_bundle_path = "/opt/spire/conf/agent/bootstrap.crt"
  trust_domain      = "faso.gov.bf"
}

plugins {
  NodeAttestor "k8s_psat" {
    plugin_data {
      cluster = "faso-prod"
    }
  }

  KeyManager "memory" {
    plugin_data {}
  }

  WorkloadAttestor "k8s" {
    plugin_data {
      skip_kubelet_verification = false
    }
  }

  WorkloadAttestor "unix" {
    plugin_data {}
  }
}

health_checks {
  listener_enabled = true
  bind_address     = "0.0.0.0"
  bind_port        = "8083"
}

telemetry {
  Prometheus {
    port = 9989
  }
}
