{{- /* SPDX-License-Identifier: AGPL-3.0-or-later */ -}}
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "notifier-ms.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notifier-ms.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "notifier-ms.selectorLabels" . | nindent 6 }}
{{- end }}
