apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: faso-loki-ds
    access: proxy
    url: ${LOKI_URL:-http://loki:3100}
    isDefault: false
    jsonData:
      maxLines: 5000
      derivedFields:
        - datasourceUid: faso-tempo-ds
          matcherRegex: '"trace_id":"(\w+)"'
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View in Tempo"
        - datasourceUid: faso-tempo-ds
          matcherRegex: 'traceId=(\w+)'
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View in Tempo"
    editable: false
    version: 1
