apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: faso-prometheus-ds
    access: proxy
    url: ${PROMETHEUS_URL:-http://prometheus:9090}
    isDefault: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: "2.45.0"
      cacheLevel: "Low"
      disableRecordingRules: false
      incrementalQueryOverlapWindow: "10m"
    editable: false
    version: 1
