apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: faso-prometheus-ds
    access: proxy
    # Prometheus runs on the host network (same as Grafana).
    url: http://127.0.0.1:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: "2.45.0"
      cacheLevel: "Low"
      disableRecordingRules: false
      incrementalQueryOverlapWindow: "10m"
    editable: false
    version: 2
