{{- /* SPDX-License-Identifier: AGPL-3.0-or-later */ -}}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "kaya.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kaya.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "kaya.fullname" . }}-vault
    creationPolicy: Owner
  data:
    - secretKey: KAYA_AUTH_PASSWORD
      remoteRef:
        key: faso/kaya/auth
        property: password
    - secretKey: KAYA_TLS_CERT
      remoteRef:
        key: faso/kaya/tls
        property: cert
    - secretKey: KAYA_TLS_KEY
      remoteRef:
        key: faso/kaya/tls
        property: key
{{- end }}
