# SPDX-License-Identifier: AGPL-3.0-only
# ClusterSecretStore — Vault KV v2 backend
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-faso
spec:
  provider:
    vault:
      server: "https://vault.faso.gov.bf"
      path: "faso"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets-sa"
            namespace: "external-secrets"
