# SPDX-License-Identifier: AGPL-3.0-only
apiVersion: v2
name: poulets-api
description: poulets-api — FASO DIGITALISATION
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - microservice
  - java
  - spring-boot
  - sovereign
maintainers:
  - name: FASO DIGITALISATION
    email: fasodigitalisation@gmail.com
annotations:
  category: Microservice
  license: AGPL-3.0-only
