// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 FASO DIGITALISATION
//
//! Re-exports of prost-generated types from the FASO xds-controller proto tree.
//!
//! Generated by `build.rs` via `tonic-build` at compile time.

/// xDS discovery protocol (ADS stream messages).
pub mod discovery {
    tonic::include_proto!("envoy.service.discovery.v3");
}

/// Cluster configuration (CDS).
pub mod cluster {
    tonic::include_proto!("envoy.config.cluster.v3");
}

/// Endpoint configuration (EDS).
pub mod endpoint {
    tonic::include_proto!("envoy.config.endpoint.v3");
}

/// Listener configuration (LDS).
pub mod listener {
    tonic::include_proto!("envoy.config.listener.v3");
}

/// Route configuration (RDS).
pub mod route {
    tonic::include_proto!("envoy.config.route.v3");
}

/// TLS secrets (SDS).
pub mod tls {
    tonic::include_proto!("envoy.extensions.transport_sockets.tls.v3");
}

/// google.rpc.Status used for NACK error_detail.
///
/// Minimal hand-written definition (we don't currently pull google/rpc/status.proto
/// through tonic-build to keep the build fast; if you need full protobuf parity,
/// add `google/rpc/status.proto` to `build.rs` and remove this module).
pub mod google_rpc {
    use prost::Message;

    #[derive(Clone, PartialEq, Message)]
    pub struct Status {
        #[prost(int32, tag = "1")]
        pub code: i32,
        #[prost(string, tag = "2")]
        pub message: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "3")]
        pub details: ::prost::alloc::vec::Vec<::prost_types::Any>,
    }
}

/// Well-known xDS v3 type URLs.
pub mod type_urls {
    pub const CLUSTER: &str = "type.googleapis.com/envoy.config.cluster.v3.Cluster";
    pub const ENDPOINT: &str =
        "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment";
    pub const LISTENER: &str = "type.googleapis.com/envoy.config.listener.v3.Listener";
    pub const ROUTE: &str = "type.googleapis.com/envoy.config.route.v3.RouteConfiguration";
    pub const SECRET: &str =
        "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret";

    pub const ALL: &[&str] = &[CLUSTER, ENDPOINT, LISTENER, ROUTE, SECRET];
}
