# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 FASO DIGITALISATION - Ministere du Numerique, Burkina Faso
# ============================================================
# Consul client agent configuration — shared by all FASO services.
# Deployed as a sidecar or DaemonSet agent; one per VM/pod.
#
# Template variables ({{ ... }}) are injected at deploy time by
# Vault Agent, Helm, or init-secrets.sh.
# ============================================================

datacenter = "bf-ouaga-1"
data_dir   = "/opt/consul/data"

retry_join = ["consul-server.service.consul"]

# Gossip encryption — key generated by `consul keygen` and stored
# in Vault at faso/consul/gossip.encrypt_key.
encrypt = "{{ CONSUL_ENCRYPT_KEY }}"

# mTLS between agents
verify_incoming        = true
verify_outgoing        = true
verify_server_hostname = true

ca_file   = "/etc/consul/tls/ca.pem"
cert_file = "/etc/consul/tls/cert.pem"
key_file  = "/etc/consul/tls/key.pem"

# Telemetry — expose Prometheus metrics on :9107/metrics
telemetry {
  prometheus_retention_time = "60s"
  disable_hostname          = true
}

# Performance tuning for latency-sensitive service mesh
performance {
  raft_multiplier = 1
}
