{{- /* SPDX-License-Identifier: AGPL-3.0-or-later */ -}}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "poulets-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "poulets-api.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "poulets-api.fullname" . }}-vault
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: faso/poulets-api/database
        property: url
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: faso/poulets-api/database
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: faso/poulets-api/database
        property: password
    - secretKey: KAYA_PASSWORD
      remoteRef:
        key: faso/poulets-api/kaya
        property: password
    - secretKey: REDPANDA_SASL_PASSWORD
      remoteRef:
        key: faso/poulets-api/redpanda
        property: password
{{- end }}
