# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 FASO DIGITALISATION
# Thanos Query frontend — federated query across sidecar + store gateway.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: faso-observability
  labels:
    app.kubernetes.io/name: thanos-query
    sovereignty: faso-digitalisation
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-query
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-query
    spec:
      containers:
        - name: thanos-query
          image: quay.io/thanos/thanos:v0.35.0
          args:
            - query
            - --store=dnssrv+_grpc._tcp.thanos-store.faso-observability.svc
            - --store=dnssrv+_grpc._tcp.thanos-sidecar.faso-observability.svc
            - --query.auto-downsampling
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
