{{- /* SPDX-License-Identifier: AGPL-3.0-or-later */ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "armageddon.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armageddon.labels" . | nindent 4 }}
data:
  ARMAGEDDON_LISTEN_ADDR: "0.0.0.0:8080"
  ARMAGEDDON_QUIC_ADDR: "0.0.0.0:4433"
  ARMAGEDDON_ADMIN_ADDR: "127.0.0.1:9903"
  RUST_LOG: "armageddon=info,pingora=warn"
