{{- /* SPDX-License-Identifier: AGPL-3.0-or-later */ -}}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "armageddon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armageddon.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "armageddon.fullname" . }}-vault
    creationPolicy: Owner
  data:
    - secretKey: ARMAGEDDON_ADMIN_TOKEN
      remoteRef:
        key: faso/armageddon/admin
        property: token
    - secretKey: ARMAGEDDON_TLS_CERT
      remoteRef:
        key: faso/armageddon/tls
        property: cert
    - secretKey: ARMAGEDDON_TLS_KEY
      remoteRef:
        key: faso/armageddon/tls
        property: key
{{- end }}
