{{- /* SPDX-License-Identifier: AGPL-3.0-or-later */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "armageddon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armageddon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.quicPort }}
      targetPort: quic
      protocol: UDP
      name: quic
  selector:
    {{- include "armageddon.selectorLabels" . | nindent 4 }}
